dist: bionic

install:
  - sudo apt update

script:
  - ./test/kicad_test.sh
  - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
  - bash merge_if_success.sh | tee merge.log
